# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    equipment_directory: '%kernel.project_dir%/public/uploads/equipment'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%equipment_directory%'
    App\Entity\Rent:
        public: false
    # Rent final price register decorators        
    App\Decorator\Rent\FinalPrice\TransportDecorator:
        arguments:
             $finalPrice: '@App\Decorator\Rent\FinalPrice\BaseFinalPrice'
        public: false
        tags:
            - { name: 'app.final_price_decorator' }
   
    App\Decorator\Rent\FinalPrice\CleaningDecorator:
        arguments:
             $finalPrice: '@App\Decorator\Rent\FinalPrice\BaseFinalPrice'
        public: false
        tags:
            - { name: 'app.final_price_decorator' }

    App\Decorator\Rent\FinalPrice\InsuranceDecorator:
        arguments:
             $finalPrice: '@App\Decorator\Rent\FinalPrice\BaseFinalPrice'
        public: false
        tags:
            - { name: 'app.final_price_decorator' }        
    
    App\Factory\Rent\DecoratorRegistry:
        arguments:
            $decoratorIds: !tagged app.final_price_decorator
        public: true

    App\Factory\Rent\FinalPriceDecoratorFactory:
        arguments:
            $decoratorRegistry: '@App\Factory\Rent\DecoratorRegistry'
        public: true

    
                

                  

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones